# Generated by Django 6.1 on 2026-08-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e2ee_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
