# Generated by Django 6.1 on 2026-08-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_is_e2ee_message_edited_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='capsule_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_capsule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='locked_placeholder',
            field=models.CharField(default='🔒 This is a locked Time Capsule.', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='unlock_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
