# Generated by Django 6.1 on 2026-08-14 22:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_deleted_by_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='disappearing_timer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_view_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='view_once_opened_by',
            field=models.ManyToManyField(blank=True, related_name='opened_view_once_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
