# Generated by Django 6.1 on 2026-08-14 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_disappearing_timer_message_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('story_type', models.CharField(default='text', max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('background_gradient', models.CharField(default='from-purple-600 to-indigo-700', max_length=100)),
                ('privacy_type', models.CharField(choices=[('everyone', 'Everyone'), ('exclude', 'My Contacts Except'), ('only_share_with', 'Only Share With')], default='everyone', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_stories', to=settings.AUTH_USER_MODEL)),
                ('excluded_users', models.ManyToManyField(blank=True, related_name='excluded_stories', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='chat.story')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('story', 'viewer')},
            },
        ),
    ]
